service: lambda-slack-notification

provider:
  name: aws
  runtime: nodejs12.13
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket
            - '/*'

environment:
  EXAMPLE API_SECRET: ${ssm:nameOfAPIKey}
functions:
  slackNotifierEntry:
    handler: src/handler.slackNotifierEntry
    events:
      - http:
          path: slackNotifierEntry
          method: get
  slackNotifierTest:
    handler: src/handler.slackNotifierTest
    events:
      - http:
          path: slackNotifierTest
          method: get
custom:
  myStage: ${opt:stage, self:provider.stage}

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-parcel

package:
  exclude:
    - node_modules/**
