service: lambda-slack-notification

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: ServerlessDeploymentBucket
            - '/*'
useDotenv: true
environment:
  EXAMPLE API_SECRET: ${ssm:nameOfAPIKey}
functions:
  slackNotifierEntry:
    handler: .build/handler.slackNotifierEntry
    events:
      - http:
          path: slackNotifierEntry
          method: get
      - sns:
          arn: arn:aws:sns:us-east-1:581790362895:p3-staging-build-failure-event
  slackNotifierTest:
    handler: .build/handler.slackNotifierTest
    events:
      - http:
          path: slackNotifierTest
          method: get

package:
  exclude:
    - node_modules/**
